In [8]:
import torch
from torch import nn


In [2]:
t1 = torch.rand((3,6))
t1

tensor([[0.9041, 0.1724, 0.8665, 0.9650, 0.9044, 0.9507],
        [0.5935, 0.2036, 0.7158, 0.2032, 0.1158, 0.5202],
        [0.2977, 0.1396, 0.9110, 0.7560, 0.0491, 0.6270]])

In [3]:
t2 = torch.rand((3,3)) 
t2

tensor([[0.2794, 0.3596, 0.9198],
        [0.5517, 0.5293, 0.7042],
        [0.1445, 0.1656, 0.0077]])

In [4]:
t3, t4 = torch.split(t1, 3, dim=1)
t3, t4


(tensor([[0.9041, 0.1724, 0.8665],
         [0.5935, 0.2036, 0.7158],
         [0.2977, 0.1396, 0.9110]]),
 tensor([[0.9650, 0.9044, 0.9507],
         [0.2032, 0.1158, 0.5202],
         [0.7560, 0.0491, 0.6270]]))

In [5]:
t5 = t3 + t2
t6 = t4 + t2
t5, t6

(tensor([[1.1835, 0.5320, 1.7863],
         [1.1452, 0.7330, 1.4200],
         [0.4422, 0.3052, 0.9187]]),
 tensor([[1.2444, 1.2640, 1.8705],
         [0.7549, 0.6452, 1.2245],
         [0.9005, 0.2147, 0.6346]]))

In [6]:
t1 = torch.cat((t5, t6), dim=1)
t1

tensor([[1.1835, 0.5320, 1.7863, 1.2444, 1.2640, 1.8705],
        [1.1452, 0.7330, 1.4200, 0.7549, 0.6452, 1.2245],
        [0.4422, 0.3052, 0.9187, 0.9005, 0.2147, 0.6346]])

In [26]:
conv_t = torch.rand((1,128,1024))
conv_t

tensor([[[0.2900, 0.8509, 0.7264,  ..., 0.0065, 0.9446, 0.1797],
         [0.5046, 0.6989, 0.8539,  ..., 0.0534, 0.9434, 0.4295],
         [0.8108, 0.4767, 0.8300,  ..., 0.7621, 0.1467, 0.6529],
         ...,
         [0.3657, 0.7054, 0.0345,  ..., 0.8434, 0.9378, 0.0851],
         [0.9807, 0.2705, 0.0195,  ..., 0.0483, 0.6319, 0.0758],
         [0.3608, 0.6215, 0.5861,  ..., 0.6164, 0.3729, 0.2143]]])

In [32]:
torch.manual_seed(123)

In [67]:
conv1 = nn.Conv1d(128, 128, 4, 1, groups=128)
out = conv1(conv_t)
out

tensor([[[ 0.1864,  0.0350, -0.3666,  ..., -0.2809,  0.1803,  0.0100],
         [-0.3856, -0.5495, -0.1249,  ..., -0.1479,  0.1119, -0.2406],
         [-0.4973, -0.1661, -0.1777,  ..., -0.1808, -0.0598, -0.0958],
         ...,
         [ 0.0926,  0.4425,  0.5775,  ...,  0.0929,  0.5488,  0.1917],
         [ 0.0305,  0.2408,  0.1439,  ..., -0.1633,  0.0037,  0.1878],
         [-0.1267,  0.0195, -0.2394,  ..., -0.1168, -0.1095, -0.1469]]],
       grad_fn=<ConvolutionBackward0>)