In [1]:
import torch
import torch.nn.functional as F

In [43]:
t1 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
t2 = torch.tensor([5, 6, 7, 8, 9, 10, 11])

In [36]:
out = F.pad(t1, (0, 10 - t1.shape[0]), "constant", 50256)
print(f"{out} shape: {out.size()}")

out = F.pad(t2, (0, 10- t2.shape[0]), "constant", 0)
print(f"{out} shape: {out.size()}")

tensor([[    1,     2,     3,     4, 50256, 50256, 50256, 50256, 50256, 50256,
         50256, 50256],
        [    5,     6,     7,     8, 50256, 50256, 50256, 50256, 50256, 50256,
         50256, 50256]]) shape: torch.Size([2, 12])
tensor([ 5,  6,  7,  8,  9, 10, 11,  0,  0,  0]) shape: torch.Size([10])


In [47]:
def pad_or_trim_sequence(t: torch.Tensor, context_length: int):
    t = t[:, :context_length]
    output = F.pad(t, (0, context_length - t.shape[1]), "constant", 0)
    print(f"{output} shape: {output.size()}")


In [85]:
t1 = torch.tensor([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]])
t2 = torch.tensor([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]])
t3 = torch.tensor([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]])
t4 = torch.tensor([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]])
pad_or_trim_sequence(t=t1, context_length=5)

tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]) shape: torch.Size([2, 5])


In [86]:
t1 = t1.unsqueeze(1)
t2 = t2.unsqueeze(1)
t3 = t3.unsqueeze(1)
t4 = t4.unsqueeze(1)
print(t1.shape, t2.shape, t3.shape, t4.shape)

torch.Size([2, 1, 5]) torch.Size([2, 1, 5]) torch.Size([2, 1, 5]) torch.Size([2, 1, 5])


In [87]:
t = torch.cat([t1, t2, t3, t4], dim=1)
t.shape

torch.Size([2, 4, 5])

In [94]:
t5: torch.Tensor = torch.rand([2, 3, 4])
t5.shape


torch.Size([2, 3, 4])

In [97]:
flatten: torch.Tensor = torch.flatten(t5, 0, 1)
flatten.shape

torch.Size([6, 4])