In [1]:
import torch
import torch.nn.functional as F

In [14]:
t1 = torch.tensor([1, 2, 3, 4])
t2 = torch.tensor([5, 6, 7, 8, 9, 10, 11])

In [19]:
out = F.pad(t1, (0, 10 - t1.shape[0]), "constant", 50256)
print(f"{out} shape: {out.size()}")

out = F.pad(t2, (0, 10- t2.shape[0]), "constant", 0)
print(f"{out} shape: {out.size()}")

tensor([    1,     2,     3,     4, 50256, 50256, 50256, 50256, 50256, 50256]) shape: torch.Size([10])
tensor([ 5,  6,  7,  8,  9, 10, 11,  0,  0,  0]) shape: torch.Size([10])


In [31]:
def pad_or_trim_sequence(t: torch.Tensor, context_length: int):
    t = t[:context_length]
    output = F.pad(t, (0, context_length - t.shape[0]), "constant", 0)
    print(f"{output} shape: {output.size()}")


In [34]:
t1 = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
pad_or_trim_sequence(t=t1, context_length=20)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  0,  0,  0,  0,  0,
         0,  0]) shape: torch.Size([20])
