In [1]:
import math
import torch
import torch.nn as nn

In [3]:
position = torch.arange(0, 10, dtype=torch.float).unsqueeze(1)
position

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [4]:
div_term = torch.exp(torch.arange(0, 4, 2).float() * (-math.log(10000.0) / 3))
div_term

tensor([1.0000, 0.0022])

In [17]:
pe = torch.zeros(10, 4)
pe

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
pe[:, 0::2] = torch.sin(position * div_term)
pe

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.8415,  0.0000,  0.0022,  0.0000],
        [ 0.9093,  0.0000,  0.0043,  0.0000],
        [ 0.1411,  0.0000,  0.0065,  0.0000],
        [-0.7568,  0.0000,  0.0086,  0.0000],
        [-0.9589,  0.0000,  0.0108,  0.0000],
        [-0.2794,  0.0000,  0.0129,  0.0000],
        [ 0.6570,  0.0000,  0.0151,  0.0000],
        [ 0.9894,  0.0000,  0.0172,  0.0000],
        [ 0.4121,  0.0000,  0.0194,  0.0000]])

In [19]:
pe[:, 1::2] = torch.cos(position * div_term)
pe

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0022,  1.0000],
        [ 0.9093, -0.4161,  0.0043,  1.0000],
        [ 0.1411, -0.9900,  0.0065,  1.0000],
        [-0.7568, -0.6536,  0.0086,  1.0000],
        [-0.9589,  0.2837,  0.0108,  0.9999],
        [-0.2794,  0.9602,  0.0129,  0.9999],
        [ 0.6570,  0.7539,  0.0151,  0.9999],
        [ 0.9894, -0.1455,  0.0172,  0.9999],
        [ 0.4121, -0.9111,  0.0194,  0.9998]])

In [20]:
pe = pe.unsqueeze(0)
pe

tensor([[[ 0.0000,  1.0000,  0.0000,  1.0000],
         [ 0.8415,  0.5403,  0.0022,  1.0000],
         [ 0.9093, -0.4161,  0.0043,  1.0000],
         [ 0.1411, -0.9900,  0.0065,  1.0000],
         [-0.7568, -0.6536,  0.0086,  1.0000],
         [-0.9589,  0.2837,  0.0108,  0.9999],
         [-0.2794,  0.9602,  0.0129,  0.9999],
         [ 0.6570,  0.7539,  0.0151,  0.9999],
         [ 0.9894, -0.1455,  0.0172,  0.9999],
         [ 0.4121, -0.9111,  0.0194,  0.9998]]])

In [21]:
x = torch.tensor(
    [[[-0.7462,  0.1711,  0.0172, -1.2772],
         [-1.6879, -1.0122,  1.1333, -1.0249],
         [-1.0936, -0.7264, -1.2888,  1.5503],
         [-0.4468, -2.4408, -0.9945, -0.2820],
         [ 0.2417,  0.7968,  1.0706,  0.3965],
         [ 1.1287,  0.3529, -0.0740,  1.3907]],

        [[-0.7462,  0.1711,  0.0172, -1.2772],
         [-1.6879, -1.0122,  1.1333, -1.0249],
         [-1.0936, -0.7264, -1.2888,  1.5503],
         [-0.4468, -2.4408, -0.9945, -0.2820],
         [ 0.2417,  0.7968,  1.0706,  0.3965],
         [ 1.1287,  0.3529, -0.0740,  1.3907]]]
)
x

tensor([[[-0.7462,  0.1711,  0.0172, -1.2772],
         [-1.6879, -1.0122,  1.1333, -1.0249],
         [-1.0936, -0.7264, -1.2888,  1.5503],
         [-0.4468, -2.4408, -0.9945, -0.2820],
         [ 0.2417,  0.7968,  1.0706,  0.3965],
         [ 1.1287,  0.3529, -0.0740,  1.3907]],

        [[-0.7462,  0.1711,  0.0172, -1.2772],
         [-1.6879, -1.0122,  1.1333, -1.0249],
         [-1.0936, -0.7264, -1.2888,  1.5503],
         [-0.4468, -2.4408, -0.9945, -0.2820],
         [ 0.2417,  0.7968,  1.0706,  0.3965],
         [ 1.1287,  0.3529, -0.0740,  1.3907]]])

In [22]:
print(x.size())
print(pe.size())
y = x + pe[:, :x.size(1), :]
y

torch.Size([2, 6, 4])
torch.Size([1, 10, 4])


tensor([[[-0.7462,  1.1711,  0.0172, -0.2772],
         [-0.8464, -0.4719,  1.1355, -0.0249],
         [-0.1843, -1.1425, -1.2845,  2.5503],
         [-0.3057, -3.4308, -0.9880,  0.7180],
         [-0.5151,  0.1432,  1.0792,  1.3965],
         [ 0.1698,  0.6366, -0.0632,  2.3906]],

        [[-0.7462,  1.1711,  0.0172, -0.2772],
         [-0.8464, -0.4719,  1.1355, -0.0249],
         [-0.1843, -1.1425, -1.2845,  2.5503],
         [-0.3057, -3.4308, -0.9880,  0.7180],
         [-0.5151,  0.1432,  1.0792,  1.3965],
         [ 0.1698,  0.6366, -0.0632,  2.3906]]])