In [1]:
import torch

In [2]:
next_token_logits = torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))
next_token_logits

tensor([ 1.2411,  1.6209,  3.2171,  5.1620,  3.8358,  6.3946,  7.1692,  8.2346,
         9.0475, 10.0949])

In [3]:
top_k: int = 3
top_logits, top_pos = torch.topk(next_token_logits, top_k)
print(top_logits)
print(top_pos)

tensor([10.0949,  9.0475,  8.2346])
tensor([9, 8, 7])


In [4]:
new_logits = torch.where(condition=next_token_logits < top_logits[-1], input=torch.tensor(float('-inf')), other=next_token_logits)
new_logits

tensor([   -inf,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf,  8.2346,
         9.0475, 10.0949])

In [7]:
print(top_logits[-1].shape)
print(next_token_logits.shape)

torch.Size([])
torch.Size([10])


In [ ]:
top_k_probabilities = torch.softmax(new_logits, dim=0)
top_k_probabilities

In [ ]:
top_k_probabilities_scaled = top_k_probabilities / 0.5
top_k_probabilities_scaled

In [ ]:
probs = torch.softmax(top_k_probabilities_scaled, dim=-1)
probs

In [ ]:
idx_next = torch.multinomial(probs, num_samples=1)
idx_next