In [2]:
import torch

In [6]:
next_token_logits = torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))
next_token_logits

tensor([-0.4047,  3.9472,  4.4996,  5.0583,  4.6743,  5.9971,  7.5104,  8.0029,
         9.0135,  9.9743])

In [7]:
top_k: int = 3
top_logits, top_pos = torch.topk(next_token_logits, top_k)
print(top_logits)
print(top_pos)

tensor([9.9743, 9.0135, 8.0029])
tensor([9, 8, 7])


In [8]:
new_logits = torch.where(condition=next_token_logits < top_logits[-1], input=torch.tensor(float('-inf')), other=next_token_logits)
new_logits

tensor([  -inf,   -inf,   -inf,   -inf,   -inf,   -inf,   -inf, 8.0029, 9.0135,
        9.9743])

In [9]:
top_k_probabilities = torch.softmax(new_logits, dim=0)
top_k_probabilities

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0915, 0.2514,
        0.6571])

In [11]:
top_k_probabilities_scaled = top_k_probabilities / 0.5
top_k_probabilities_scaled

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1830, 0.5028,
        1.3142])

In [12]:
probs = torch.softmax(top_k_probabilities_scaled, dim=-1)
probs

tensor([0.0737, 0.0737, 0.0737, 0.0737, 0.0737, 0.0737, 0.0737, 0.0885, 0.1218,
        0.2741])

In [19]:
idx_next = torch.multinomial(probs, num_samples=1)
idx_next

tensor([5])